- cmd/server/main.go
- db/migrations/000004_add_profile_image_id_to_users.down.sql
- db/migrations/000004_add_profile_image_id_to_users.up.sql
- internal/database/user.go
- internal/media/service.go
- internal/models/user.go
- internal/server/router.go
- internal/server/user_handler.go
- internal/user/service.go
- internal/user/service_test.go
- internal/views/user.go
- pkg/docs/docs.go
- pkg/docs/swagger.json
- pkg/docs/swagger.yaml
사용자 요청/응답에 프로필 이미지를 추가합니다.
흐름은 다음과 같습니다.
1. Media API로 프로필 이미지를 업로드한다.
2. Media API의 응답으로 받은 Media ID를 회원가입 / 정보수정 API가 같이 넘긴다.
3. 응답으로 유저 정보와 더불어 `profileImageUrl`을 받게 된다.
> 사용자 요청/응답에 프로필 이미지를 추가합니다.

- Dockerfile
#13 이후 docker build 간에 다음과 같은 오류가 나는 이슈가 생겼습니다.
```sh
...
=> [build-stage 5/7] COPY . .
=> ERROR [build-stage 6/7] RUN CGO_ENABLED=0 GOOS=linux go build -o ./server ./cmd/server/main.go
------
> [build-stage 6/7] RUN CGO_ENABLED=0 GOOS=linux go build -o ./server ./cmd/server/main.go:
11.31 # command-line-arguments
11.31 cmd/server/main.go:39:7: undefined: NewRouter
------
Dockerfile:7
--------------------
5 |     RUN go mod download
6 |     COPY . .
7 | >>> RUN CGO_ENABLED=0 GOOS=linux go build -o ./server ./cmd/server/main.go
8 |     # migration script
9 |     RUN CGO_ENABLED=0 GOOS=linux go build -o ./migrate ./cmd/migrate/main.go
--------------------
ERROR: failed to solve: process "/bin/sh -c CGO_ENABLED=0 GOOS=linux go build -o ./server ./cmd/server/main.go" did not complete …
```
> Dockerfile에서 go build 간에 모든 .go 파일을 추가합니다.

- .github/workflows/cd.yml
CD에 사용되는 Release 태그 이름을 변경합니다.
- 어차피 release에 올라가는 것 자체가 release라는 뜻이니 `release`는 떼어냅니다.
- URL 상에서 `/`가 escape 처리되어 보기 좋지 않기 때문에 URL 친화적인 `-`로 변경합니다.
`release/dev/v1`
`dev-v1`
> CD에 사용되는 Release 태그 이름을 변경합니다.

- cmd/import_conditions/main.go
- db/migrations/000008_create_posts_table.up.sql
- internal/postgres/condition_store.go
- sos_condition 테이블의 PK를 SERIAL 타입에서 INT로 변경하였습니다.
혹여나 데이터가 삭제되어 데이터를 재적재할 때  ID(PK) 값이 변경되지 않도록 수정하였습니다.
- enum과 유사한 상수값으로 변경하면서 발생한 타입 불일치 문제를 해결하였습니다.
> 돌봄조건 데이터 적재가 되지 않는 오류를 해결합니다.

- cmd/server/handler/sos_post_handler.go
- internal/domain/sos_post/service.go
- internal/domain/sos_post/view.go
- internal/domain/user/user.go
- internal/postgres/user_store.go
- pkg/docs/docs.go
- pkg/docs/swagger.json
- pkg/docs/swagger.yaml
- 돌봄급구 수정 API에서 상황에 맞지 않게 403 에러가 반환되는 이슈를 수정하였습니다.
- 게시글 조회 Response 타입에 created_at, updated_at 를 추가하였습니다.
- Swagger 돌봄급구 API에서 불필요한 Security를 제거하였습니다.
_/posts/sos [PUT]_
Request (예시)
```
{
"care_type": "foster",
"carer_gender": "male",
"condition_ids": [
1, 2, 3
],
"content": "content",
"date_end_at": "2020-10-06T10:00:00+09:00",
"date_start_at": "2020-10-16T18:00:00+09:00",
"id": 1,
"image_ids": [
1
],
"pet_ids": [
1
],
"reward": "string",
"reward_amount": "hour",
"time_end_at": "10:00",
"time_start_at": "18:00",
"title": "title"
}
```
> 돌봄급구 수정 API 에러를 해결합니다.

- cmd/server/handler/breed_handler.go
- cmd/server/handler/sos_post_handler.go
- cmd/server/handler/user_handler.go
- cmd/server/main.go
- cmd/server/router.go
- docker-compose-test.yml
- internal/common/web.go
- internal/domain/pet/breed_service.go
- internal/domain/user/service.go
- internal/domain/user/tests/service_test.go
- internal/domain/user/user.go
- internal/postgres/breed_store.go
- internal/postgres/user_store.go
- pkg/docs/docs.go
- pkg/docs/swagger.json
- pkg/docs/swagger.yaml
사용자 목록 조회 API를 추가합니다.
`GET /api/users`로 접근 가능하며, nickname 쿼리를 받아 일치하는 유저를 조회합니다. 아무것도 안넣으면 전체 검색으로 진행됩니다.
- 응답에서 민감 정보는 모두 제외했지만, 일단 인증을 필요로 하도록 했습니다.
- 추가로 기존 견/묘종 목록 조회 API에서 SQL injection 가능성이 있어 해당 부분을 수정하고, 아무 견/묘종이 없을 경우 빈 배열 대신 null이 나가고 있어서 해당 부분을 수정합니다.
- API 버전은 0.7.0으로 올립니다.
- Test DB docker-compose의 pg, migrate 버전도 로컬 개발 DB에 맞게 올립니다.
> 사용자 목록 조회 API를 추가합니다.

- api/common.go
- cmd/server/handler/breed_handler.go
- cmd/server/handler/sos_post_handler.go
- cmd/server/handler/user_handler.go
- internal/domain/pet/breed.go
- internal/domain/pet/breed_service.go
- internal/domain/pet/view.go
- internal/domain/sos_post/condition_service.go
- internal/domain/sos_post/service.go
- internal/domain/sos_post/sos_post.go
- internal/domain/sos_post/tests/service_test.go
- internal/domain/sos_post/view.go
- internal/domain/user/service.go
- internal/domain/user/tests/service_test.go
- internal/domain/user/user.go
- internal/postgres/breed_store.go
- internal/postgres/sos_post_store.go
- internal/postgres/user_store.go
- pkg/docs/docs.go
- pkg/docs/swagger.json
- pkg/docs/swagger.yaml
마지막 페이지 여부 `is_last_page`를 반환합니다.
가장 오버헤드가 적은 것으로 보이는, size + 1만큼 가져와 길이 비교하는 방식으로 진행했습니다. 이는 `PaginatedView` struct의 `CalcLastPage` 함수로 진행합니다.
추가로 돌봄급구 조건 목록 조회 API에서 nil array가 반환되는 이슈를 수정합니다.
> 마지막 페이지 여부를 반환합니다.

- cmd/server/handler/sos_post_handler.go
- internal/domain/sos_post/service.go
- internal/domain/sos_post/sos_post.go
- internal/domain/sos_post/tests/service_test.go
- internal/postgres/sos_post_store.go
- 페이지네이션 파라미터를 `Prepared Statements`로 조회하도록 수정하였습니다.
부득히하게 ORDER BY 옵션의 경우, Prepared Statements로 파라미터를 삽입하지 못하기 때문에 switch문으로 체크하고 문자열로 대입하도록 구현하였습니다. 이 방법은 Injection 문제를 완전히 해결한게 아니다보니 `switch`문의 `default`를 제거하고 정해놓은 형식(newest, deadline)의 값만 삽입하도록 해야할 지 고민 중입니다.
- 작성자 ID로 돌봄 급구 게시글 조회 로직에 정렬 기준(newest, deadline)을 추가하였습니다.
정렬 기능은 전체 조회에만 구현되어 있어, 작성자 ID로 조회하는 경우에는 사용할 수 없었습니다. 
같은 엔드포인트에서 동작하기 때문에 혼란을 줄 수 있고 추후에 필터링 옵션이 추가될 가능성을 고려하여 추가하였습니다.
> 돌봄급구 SQL Injection 문제를 해결합니다.

- api/errors.go
- api/web.go
- cmd/import_breeds/main.go
- cmd/server/main.go
- go.mod
- go.sum
- internal/infra/database/transaction.go
- internal/service/tests/sos_post_service_test.go
에러 로그를 추가하고 일부 버그를 수정합니다.
- AppError 생성자에 AppError를 넣은 이슈
- RegisterUser 간 잘못된 에러 반환하는 이슈
- page / size가 0 이하일 때 panic이 일어나는 이슈
로깅 라이브러리는 [zerolog](https://github.com/rs/zerolog)를 사용합니다.
> 에러 로그를 추가하고 일부 버그를 수정합니다.

- internal/domain/sos_post/sos_post.go
- internal/domain/sos_post/view.go
상관없음을  `unspecified` 나타낼 계획이었으나 최대 글자수가 10으로 설정 되어 있어 부득이하게 `fine` 표현했습니다.
> 돌봄 조건 중 성별에 상관없음을 추가합니다.

- cmd/server/handler/user_handler.go
- cmd/server/router.go
- db/migrations/000008_create_posts_table.down.sql
- db/migrations/000011_deleted_user_uix.down.sql
- db/migrations/000011_deleted_user_uix.up.sql
- internal/domain/user/user.go
- internal/postgres/user_store.go
- internal/service/user_service.go
Soft delete 방식으로 진행합니다. 기존 user의 unique index를 변경합니다.
hard delete 구현보다 이게 나을 것 같아서 이 방향으로 합니다.
> 회원탈퇴 API를 추가합니다.

- db/migrations/000012_timestamp_with_timezone.down.sql
- db/migrations/000012_timestamp_with_timezone.up.sql
기존 created_at, updated_at, deleted_at 컬럼의 타입이 `timestamp`(timestamp without timezone)로 설정되어 있어 timezone 정보가 누락되어 있었습니다.
`timestampz`(timestamp with timezone) 필드로 설정하여 timezone을 저장합니다. timezone은 UTC를 사용합니다.
배포 후 `migrate` 명령어 실행이 필요합니다.
> 날짜 컬럼을 `timestampz`(timetamp with timezone) 타입으로 변경합니다.

- internal/infra/database/transaction.go
Transaction Rollback 함수 실행 간 이미 transaction이 commit 됐을 때 나오는 에러를 무시합니다.
Transaction을 BeginTx로 시작하고 defer Rollback 함수를 넣는데 되는데, commit 여부와 상관 없이 rollback 함수는 무조건 실행되고, 이후 commit이 되더라도 에러가 나오기 때문에 에러 처리를 하지 않더라도 logger에 의해 에러가 로그에 찍히는 마이너한 이슈가 있습니다.
로그가 나오지 않도록 ErrTxDone 오류일 경우 무시합니다.
```
sql: transaction has already been committed or rolled back
```
(마이너한 이슈라 리뷰 안받고 머지할게요.)
> Transaction Rollback 함수 실행 간 이미 transaction이 commit 됐을 때 나오는 에러를 무시합니다.

- cmd/server/handler/user_handler.go
- cmd/server/main.go
- cmd/server/router.go
- internal/domain/pet/pet.go
- internal/domain/pet/request.go
- internal/domain/pet/view.go
- internal/postgres/pet_store.go
- internal/service/tests/user_service_test.go
- internal/service/user_service.go
- internal/tests/factories.go
- internal/tests/service.go
내 반려동물 수정 / 삭제 API를 추가합니다.
- `PUT /users/me/pets/{petID}`: 내 반려동물 수정
- `DELETE /users/me/pets/{petID}`: 내 반려동물 삭제
추가로 Pet 요청(`pet/request.go`로 분리) 및 `UserService` 테스트 코드 리팩터링합니다.
\* 버전업 0.11.0 -> 0.12.0
> 내 반려동물 수정 / 삭제 API를 추가합니다.

- docker-compose-test.yml
- docker-compose.yml
docker-compose 파일에서 deprecated 된 version property를 제거합니다.
```
WARN[0000] .../pets-next-door-api/docker-compose-test.yml: `version` is obsolete
```
https://docs.docker.com/compose/compose-file/04-version-and-name/#version-top-level-element-obsolete
> docker-compose 파일에서 version property를 제거합니다.

- cmd/server/router.go
- internal/wschat/server.go
#80 에서 추가된 채팅 기능을 참고하고, 일시적으로 해당 코드는 주석처리 했습니다.
현재 가능한 기능은 WS 접속 후 메시지 전송입니다.
WS endpoint는 `GET /ws/chat`, Authorization 헤더를 넘겨줘야 합니다.
`sender.id`는 Authorization 헤더에 따라 자동으로 추가됩니다.
User 1이 받는 내용
```json
{
"room": {
"id": 1
},
"messageType": "plain",
"message": "hello"
}
```
User 2가 받는 내용
```json
{
"user": {
"id": 1
},
"room": {
"id": 1
},
"messageType": "plain",
"message": "hello",
"createdAt": "2024-07-28T15:56:14",
"updatedAt": "2024-07-28T15:56:14"
}
```
> 인증된 채팅 기능 초안을 추가합니다.

- .github/workflows/ci.yml
- internal/wschat/server.go
클라이언트에서 보낸 메시지와 대조, 필터링하기 위한 Message ID를 추가합니다.
클라이언트에서 보낸 그대로 보냅니다.
> WS chat에 Message ID를 추가합니다.

- .golangci.yml
- internal/configs/server.go
- internal/tests/config.go
golangci-lint 룰을 일부 수정합니다.
1. deprecated된 `execinquery` 린터를 제거합니다. 그냥 insert/update할 땐 `Query` 대신 `Exec`을 사용하면 됩니다.
```
internal/tests/config.go:7:1: directive `//nolint:gochecknoinits` is unused for linter "gochecknoinits" (nolintlint)
```
2. `gochecknoinits`가 린터에서 `init`이라는 이름을 쓰는 것에 대해 임시로 처리합니다.
nolint를 걸어놨는데도 최근 들어 lint 에러가 뜨길래 봤더니 이름을 `init`으로 쓰고 있는 듯 합니다. 이슈를 보니 고쳐진 듯 하지만 임시로 제거합니다.
> golangci-lint 룰을 일부 수정합니다.

- internal/domain/chat/model.go
- internal/domain/chat/view.go
- internal/infra/database/gen/chats.sql.go
- internal/service/chat_service.go
- queries/chats.sql
1. 전체 채팅 및 채팅방의 ID값을 UUID를 사용하도록 수정 
2. 채팅방 메시지 조회시 기존 하나의 쿼리로 통합되어있던 항목을 각 분기별로 쿼리를 나눠서 진행하도록 수정 
- prev, next 와 같이 파라미터에 각 어떠한 값이 들어올지 모르고, 특정된 파라미터 값이 들어왔을때 들어온 값을 기준으로 쿼리에 질의하기 위함 
- 동적쿼리로 진행하기 위해선, 현재 컨벤션 ( query sql 작성 후 생성 )을 하지 못하고, service 내 쿼리를 포함시켜야 함 
- 복잡한 쿼리연산을 통한 비용보다 필요한 항목만 질의하여 쿼리 비용을 절약하기 위함 
- prev, next 와 같은 파라미터값이 주어지지 않을경우 최신 메시지를 기준으로 파라미터내 size만큼 조회를 진행 ( DESC ) 
- prev 값만 주어질 경우 해당 메시지를 기준으로 최신 메시지 순서로 리스트 조회를 진행 ( DESC ) 
- next 값만 주어질 경우 해당 메시지를 기준으로 메시지 리스트 조회를 진행 ( ASC )
> refactor : 채팅 서비스의 UUID 사용을 하도록 수정하고, 조회 항목의 리펙토링을 진행합니다.

- .github/workflows/ci.yml
- .golangci.yml
- Dockerfile
- flake.lock
- flake.nix
- go.mod
golangci-lint에서 너무 많은 램 사용량(16GB+)을 보여서 봤더니 go와 golangci-lint의 go 버전 불일치로 인한 이슈였습니다.
Go 버전을 업데이트합니다.
> Go 1.22 -> 1.23 업데이트합니다.

- .golangci.yml
- api/errors.go
- api/web.go
- cmd/import_breeds/main.go
- cmd/import_conditions/main.go
- cmd/migrateuuids/main.go
- cmd/migrateuuids/uuidmigrator.go
- cmd/server/handler/auth_handler.go
- cmd/server/handler/breed_handler.go
- cmd/server/handler/chat_handler.go
- cmd/server/handler/condition_handler.go
- cmd/server/handler/media_handler.go
- cmd/server/handler/sos_post_handler.go
- cmd/server/handler/user_handler.go
- cmd/server/router.go
- internal/common/null.go
- internal/datatype/uuid.go
- internal/infra/bucket/client.go
- internal/infra/database/transaction.go
- internal/service/auth_service.go
- internal/service/breed_service.go
- internal/service/chat_service.go
- internal/service/media_service.go
- internal/service/sos_condition_service.go
- internal/service/sos_post_service.go
- internal/service/tests/sos_post_service_test.go
- internal/service/tests/user_service_test.go
- internal/service/user_service.go
- internal/tests/service.go
- internal/wschat/server.go
- 서비스 함수의 시그니처가 항상 `error` 대신 `*pnd.AppError`로 강제되어 비즈니스 로직과 별개로 존재하는 함수도 래핑해서 생성해야 했음.
- 호환되지 않는 두 타입 `error`와 `*pnd.AppError`가 혼재하여 `err` 외에도 `err2`, `err3`을 써야하는 경우가 많았음.
- AppError가 나가는 방식은 항상 `c.JSON(appErr.code, appErr.response)`로 동일한데 매번 명시해줘야 했음.
- DB 에러 발생 시 `FromPostgresError`를 까먹고 안하면 문제 발생.
- `pnd.AppError`은 [error 인터페이스](https://go.dev/tour/methods/19)를 구현합니다.
- `router.go`에 에러 미들웨어를 추가해 `AppError`, `FromPostgresError`를 한 곳에서 처리합니다.
- 기존 서비스 코드에서 Error를 발생하는 함수에는 error을 반환하도록 하고, 에러 유틸을 이용해 응답을 만듭니다.
- 기존 코드에서 DB 에러 발생 시 `FromPostgresError` 래핑하는 부분 일괄 제거합니다.
앞으로 이렇게 서비스 함수를 작성하면 됩니다.
1. 함수에서 error가 발생한다면 정의 부분에선 항상 `error` 타입으로 넣어줍니다.
2. DB 에러 발생시에는 그냥 `return err` 해주면 됩니다. (`FromPostgresError`는 직접 호출하지 않습니다.)
3. 이외의 에러는 기존처럼 에러 응답을 만들 땐 에러 유틸 코드를 이용해 응답을 만들어 반환합니다.
4. 서비스에서 …
> 커스텀 에러를 error 미들웨어에서 처리합니다.
